version: "3.8"

services:
  app:
    image: ghcr.io/indy-center/controller-tools:${IMAGE_TAG}
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${APP_NAME}-${IMAGE_TAG}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-${IMAGE_TAG}.entrypoints=websecure"
      - "traefik.http.services.${APP_NAME}-${IMAGE_TAG}.loadbalancer.server.port=${APP_PORT}"
      - "traefik.http.routers.${APP_NAME}-${IMAGE_TAG}.tls.certresolver=myresolver"
    secrets:
      - controller-tools-database-url
    entrypoint: >
      sh -c "export DATABASE_URL=$$(cat /run/secrets/controller-tools-database-url) && node build"

networks:
  web:
    external: true

secrets:
  controller-tools-database-url:
    external: true