version: "3.8"

services:
  app:
    image: ghcr.io/indy-center/controller-tools:${IMAGE_TAG}
    networks:
      - web
    secrets:
      - controller-tools-database-url
    entrypoint: >
      sh -c "export DATABASE_URL=$$(cat /run/secrets/controller-tools-database-url) && node build"
    deploy:
      update_config:
        order: start-first
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.${APP_NAME}.entrypoints=websecure"
        - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=${APP_PORT}"
        - "traefik.http.routers.${APP_NAME}.tls.certresolver=myresolver"
networks:
  web:
    external: true
secrets:
  controller-tools-database-url:
    external: true