version: "3.8"

services:
  app:
    image: ghcr.io/indy-center/controller-tools:${IMAGE_TAG}
    environment:
      - NON_SECRET_ENV_VAR=example_value
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.controller-tools-${IMAGE_TAG}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.controller-tools-${IMAGE_TAG}.entrypoints=websecure"
      - "traefik.http.services.controller-tools-${IMAGE_TAG}.loadbalancer.server.port=3000"
      - "traefik.http.routers.controller-tools-${IMAGE_TAG}.tls.certresolver=myresolver"
    secrets:
      - controller-tools-database-url
    entrypoint: >
      sh -c "export DATABASE_URL=$$(cat /run/secrets/controller-tools-database-url) && node build"

networks:
  web:
    external: true

secrets:
  controller-tools-database-url:
    external: true