name: Build

on:
  push:
    branches:
      - main
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  # Builds the Docker image, pushes it to the registry, and attests the build
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: ${{ github.sha }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: https://tools.chasingthe.cloud
    if: github.ref == 'refs/heads/main'
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Docker Stack Deploy"
        uses: jtwebman/stack-deploy-action@proposed_registry_login_change
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOMAIN: 'tools.chasingthe.cloud'
          APP_PORT: 3000
          APP_NAME: 'controller-tools'
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_KEY }}
          file: "docker-compose.yaml"
          name: 'controller-tools'
          registry_auth: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment:
      name: 'Development'
      url: https://dev.tools.chasingthe.cloud
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: "Docker Stack Deploy"
        uses: jtwebman/stack-deploy-action@proposed_registry_login_change
        env:
          IMAGE_TAG: ${{ github.sha }}
          DOMAIN: 'dev.tools.chasingthe.cloud'
          APP_PORT: 3000
          APP_NAME: 'controller-tools-dev'
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_KEY }}
          file: "docker-compose.yaml"
          name: 'controller-tools-dev'
          registry_auth: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin