name: Build and Deploy Development

on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      attestations: write
      id-token: write
    outputs:
      build_number: ${{ steps.build_number.outputs.build_number }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate build number
        id: build_number
        run: |
          echo "build_number=${GITHUB_RUN_NUMBER}" >> $GITHUB_OUTPUT

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.build_number.outputs.build_number }}
            type=raw,value=${{ github.sha }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          build-args: |
            BUILD_NUMBER=${{ steps.build_number.outputs.build_number }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

  deploy-development:
    name: Deploy to Development
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 'Docker Stack Deploy'
        uses: jtwebman/stack-deploy-action@proposed_registry_login_change
        env:
          IMAGE_TAG: ${{ needs.build.outputs.build_number }}
          DOMAIN: 'tools.dev.zid-internal.com'
          APP_PORT: 3000
          APP_NAME: 'controller-tools'
          BUILD_NUMBER: ${{ needs.build.outputs.build_number }}
        with:
          host: ${{ secrets.DEPLOY_HOST_DEV }}
          user: ${{ secrets.DEPLOY_USER }}
          ssh_key: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          file: 'docker-compose.yaml'
          name: 'controller-tools'
          registry_auth: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
